### ISSUE TITLE
Addon-agent container with image tag latest instead of fixed version

### ISSUE THREAD

**Issue by rtrive** [open-cluster-management-io/cluster-proxy#114]
Hi Guys!

I've a problem with the `addon-agent` container that has a wrong image with the tag latest instead of a fixed version. I check the code and it seems all right but unfortunately, when I deploy the cluster-proxy on a managed cluster the containers of deployment have these values:

```yaml
containers:
      - args:
        - --proxy-server-host=127.0.0.1
        - --proxy-server-port=8091
        - --agent-identifiers=host=dev&host=dev.open-cluster-management-cluster-proxy&host=dev.open-cluster-management-cluster-proxy.svc.cluster.local
        - --ca-cert=/etc/ca/ca.crt
        - --agent-cert=/etc/tls/tls.crt
        - --agent-key=/etc/tls/tls.key
        command:
        - /proxy-agent
        image: quay.io/open-cluster-management/cluster-proxy:v0.2.0
        imagePullPolicy: IfNotPresent
        name: proxy-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ca
          name: ca
          readOnly: true
        - mountPath: /etc/tls
          name: hub
          readOnly: true
      - args:
        - --v=2
        - --hub-kubeconfig=/etc/kubeconfig/kubeconfig
        - --cluster-name=dev
        - --proxy-server-namespace=open-cluster-management-addon
        - --enable-port-forward-proxy=true
        command:
        - /agent
        image: quay.io/open-cluster-management/cluster-proxy:latest
        imagePullPolicy: IfNotPresent
        name: addon-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubeconfig/
          name: hub-kubeconfig
          readOnly: true
```

as you can see the `proxy-agent` container has version `v0.2.0` instead the `addon-agent` has the latest version that is causing crashloopbackoff errors. 
Why they don't have the same version? I'll attach also the ManagedProxy configuration

```yaml
apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ManagedProxyConfiguration
metadata:
  name: cluster-proxy
spec:
  authentication:
    dump:
      secrets:
        signingAgentServerSecretName: agent-server
        signingProxyClientSecretName: proxy-client
        signingProxyServerSecretName: proxy-server
    signer:
      type: SelfSigned
  proxyAgent:
    image: quay.io/open-cluster-management/cluster-proxy:v0.2.0
    replicas: 3
  proxyServer:
    entrypoint:
      port: 8091
      type: PortForward
    image: quay.io/open-cluster-management/cluster-proxy:v0.2.0
    inClusterServiceName: proxy-entrypoint
    namespace: open-cluster-management-addon
    replicas: 3
```

Thanks!

**Comment by yue9944882** [comment]
@rtrive i think it's fixed by https://github.com/open-cluster-management-io/cluster-proxy/pull/87. can you try install the latest release i.e. v0.2.1

**Comment by rtrive** [comment]
in my case #87 doesn't fix the problem because is that change that allows addon-agent to have a different version of proxy-agent causing crash with the latest release

**Comment by yue9944882** [comment]
@rtrive if i recall correctly the fix https://github.com/open-cluster-management-io/cluster-proxy/pull/87 are connected w/ this issue, another cause was that the agent image version in the helm chart diverged w/ the release version. anyway i'm pretty sure it's fixed in the new release. cc @xuezhaojun if you can find the fix PR for us.

**Comment by xuezhaojun** [comment]
Hello, @rtrive  Here is the reason why proxy-agent and addon-agent are using different images.

Under cluster-proxy, we are using another repo [ANP](https://github.com/kubernetes-sigs/apiserver-network-proxy) to support connectivity. And `proxy-agent` & `proxy-server` are built from this repo.

In some cases, users already have an ANP image in their repository, and they want to use their anp image instead of binaries in cluster-proxy for security concerns.

**Comment by xuezhaojun** [comment]
Can we also take a look of the status of `cluster-proxy-addon-manager`? Because if the flag `agent-image-name` is set, the `addon-proxy` will use this image.

The `addon-proxy` will use the same image as `proxy-agent` only if this flag is not set.
